version: "3" # composeファイルのバージョン
services:
    app:
        # サービス名
        build: . # ビルドに使うDockerfileの場所
        tty: true # コンテナの永続化
        ports:
            # ホストOSのポートとコンテナのポートをつなげる 
            - "80:80"
        depends_on:
            mysql:
                condition: service_healthy

    mysql:
        build: ./mysql/
        # volumes:
        #     # 初期データを投入するSQLが格納されているdir
        #     - ./mysql/init:/docker-entrypoint-initdb.d
        #     # 永続化するときにマウントするdir
        #     - ./mysql/data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=golang
            # ports:
            - "3306:3306"
        container_name: kann-dev-db-container
        healthcheck:
            test:
                [
                    "CMD",
                    "mysqladmin",
                    "ping",
                    "-h",
                    "localhost",
                    "-uroot",
                    "-pgolang" # "mysql --defaults-extra-file=/dbaccess.cnf"
                ]
            retries: 3
